name: Deploy to Maven Central snapshot
on: pull_request
jobs:
  prepare_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch
      - name: "Set output"
        id: set-output
        run: echo "mix_drinks_core_version=${{ steps.bump-semver.outputs.new_version }}-`echo "${GITHUB_SHA}" | cut -c1-8`" >> $GITHUB_OUTPUT
      - name: "Print output"
        run: echo ${{ steps.set-output.outputs.mix_drinks_core_version }}
    outputs:
      output_write_mix_drinks_code_version: ${{ steps.set-output.outputs.mix_drinks_core_version }}
  deploy:
    needs: [ prepare_deploy ]
    runs-on: macos-13
    steps:
      - name: Print MIX_DRINKS_CORE_VERSION
        run: echo ${{ needs.prepare_deploy.outputs.output_write_mix_drinks_code_version }}
      - name: "checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        env:
          MIX_DRINKS_CORE_VERSION: ${{ needs.prepare_deploy.outputs.output_write_mix_drinks_code_version }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: ./gradlew publishAllPublicationsToMavenRepository
