name: Deploy to Maven Central release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - name: Print MIX_DRINKS_CORE_VERSION
        run: echo ${{ github.ref_name }}
      - name: "checkout"
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        env:
          MIX_DRINKS_CORE_VERSION: ${{ github.ref_name }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: ./gradlew publishAllPublicationsToMavenRepository
