name: Deploy to Maven Central snapshot
on: pull_request
jobs:
  prepare_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
      - name: Print version
        run: echo ${{ steps.get_next_version.outputs.version }}
      - name: Write sha to evn as MIX_DRINKS_CORE_VERSION
        id: step_write_mix_drinks_code_version
        run: echo "MIX_DRINKS_CORE_VERSION=${{ steps.get_next_version.outputs.version }}-`echo "${GITHUB_SHA}" | cut -c1-8`" >> $GITHUB_OUTPUT
    outputs:
      output_write_mix_drinks_code_version: ${{ steps.step_write_mix_drinks_code_version.outputs.MIX_DRINKS_CORE_VERSION }}
  deploy:
    runs-on: macos-12
    steps:
      - name: Print MIX_DRINKS_CORE_VERSION
        env:
          TEST_MIX_DRINKS_CORE_VERSION: ${{ needs.prepare_deploy.outputs.output_write_mix_drinks_code_version }}
        run: echo $TEST_MIX_DRINKS_CORE_VERSION
      - name: "checkout"
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        env:
          MIX_DRINKS_CORE_VERSION: ${{ needs.prepare_deploy.outputs.output_write_mix_drinks_code_version }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: ./gradlew publishAllPublicationsToMavenRepository
