name: Linter (detekt)
on: pull_request
jobs:
  detekt:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.1
