name: Linter (detekt)
on: pull_request
jobs:
  detekt:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.3
