name: Linter (detekt)
on: pull_request
jobs:
  detekt:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.4
